resume_website/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #path('url address', 'view', 'name')
    path('',include('website.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *
app_name = 'website'
urlpatterns = [
    path('',index_view,name="index"),
    path('resume',resume_view,name="resume"),
    path('projects',project_view,name="projects"),
    path('contact',contact_view,name="contact")
]

website/models.py
from django.db import models

# Create your models here.

website/views.py
from django.shortcuts import render


def index_view(request):
    context = {"biography" : ["My name is Sadra Salehi Kordabadi",
                              "I started my coding journey with cpp but then i became interested in web development so i tried to learn things that i need to know about it.",
                              "Currenly i am trying to learn Django for Backend development."
                              ]}
    return render(request,'website/index.html',context=context)

def resume_view(request):
    context = {"skills" : ["Web Development","Automation Testing", "UI/UX Design"],
               "languages" : ["Persian","English","French"],
               "education" : "Bachelor of Computer Engineering"
               }
    return render(request,'website/resume.html',context=context)

def project_view(request):
    context = {"project_link" : "https://github.com/sadra13810129/resume_webiste"}
    return render(request,'website/projects.html',context=context)

def contact_view(request):
    context = {"Email" : "sadra13810129@gmail.com", "Telegram" : "@OriginalPlaymaker29", "Phone_Number" : "0910-124-5263"}
    return render(request,'website/contact.html',context=context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>CV Website</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Custom Google font-->
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@100;200;300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body class="d-flex flex-column h-100">
        <main class="flex-shrink-0">
            <!-- Navigation-->
            <nav class="navbar navbar-expand-lg navbar-light bg-white py-3">
                <div class="container px-5">
                    <a class="navbar-brand" href="index.html"><span class="fw-bolder text-primary">CV Website</span></a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto mb-2 mb-lg-0 small fw-bolder">
                            <li class="nav-item"><a class="nav-link" href="{% url 'website:index' %}">Home</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'website:resume' %}">Resume</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'website:projects' %}">Projects</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'website:contact' %}">Contact</a></li>
                        </ul>
                    </div>
                </div>
            </nav>


            {% block content %}
            {% endblock %}


             <!-- Footer-->
        <footer class="bg-white py-4 mt-auto">
            <div class="container px-5">
                <div class="row align-items-center justify-content-between flex-column flex-sm-row">
                    <div class="col-auto"><div class="small m-0">Copyright &copy; Your Website 2023</div></div>
                    <div class="col-auto">
                        <a class="small" href="#!">Privacy</a>
                        <span class="mx-1">&middot;</span>
                        <a class="small" href="#!">Terms</a>
                        <span class="mx-1">&middot;</span>
                        <a class="small" href="#!">Contact</a>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

templates/website/contact.html
{% extends "base.html" %}
{% block content %}
{% load static %}
            <!-- Page content-->
            <section class="py-5">
                <div class="container px-5">
                    <div class="bg-light rounded-4 py-5 px-4 px-md-5">
                        <div class="text-center mb-5">
                            <h1 class="fw-bolder">Stay in touch with me</h1>
                        </div>
                        <div class="card shadow border-0 rounded-4 mb-5">
                            <!--Email-->
                            <div class="card-body p-5">
                                <div class="mb-0">
                                    <div class="d-flex align-items-center mb-4">
                                        <div class="feature bg-primary bg-gradient-primary-to-secondary text-white rounded-3 me-3"><i class="bi bi-tools"></i></div>
                                        <h3 class="fw-bolder mb-0"><span class="text-gradient d-inline"><a href="mailto:{{Email}}">{{Email}}</a></span></h3>
                                    </div>
                                </div>
                                <!-- Telegram-->
                                <div class="mb-0">
                                    <div class="d-flex align-items-center mb-4">
                                        <div class="feature bg-primary bg-gradient-primary-to-secondary text-white rounded-3 me-3"><i class="bi bi-telegram"></i></div>
                                        <h3 class="fw-bolder mb-0"><span class="text-gradient d-inline">{{Telegram}}</span></h3>
                                    </div>
                                </div>
                                <!-- Phone Number-->
                                <div class="mb-0">
                                    <div class="d-flex align-items-center mb-4">
                                        <div class="feature bg-primary bg-gradient-primary-to-secondary text-white rounded-3 me-3"><i class="bi bi-telephone-fill"></i></div>
                                        <h3 class="fw-bolder mb-0"><span class="text-gradient d-inline">{{Phone_Number}}</span></h3>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </main>
{% endblock %}

templates/website/index.html
{% extends "base.html" %}
{% block content %}
	{% load static %}

            <!-- BioGhrapy Section-->
            <section class="bg-light py-5">
                <div class="container px-5">
                  <div class="col-xxl-7">
                    <!-- Header profile picture-->
                    <div class="d-flex justify-content-center ">
                        <div class="profile bg-gradient-primary-to-secondary">
                            <!-- TIP: For best results, use a photo with a transparent background like the demo example below-->
                            <!-- Watch a tutorial on how to do this on YouTube (link)-->
                            <img class="profile-img" src="{% static 'assets/Myprofile.png' %}" alt="..." />

                                <!-- END of SVG dots-->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
                    <div class="row gx-5 justify-content-center">
                        <div class="col-xxl-8">
                            <div class="text-center my-5">
                                <h2 class="display-5 fw-bolder"><span class="text-gradient d-inline">Biography</span></h2>
                                <p class="lead fw-light mb-4">{{biography.0}}</p>
                                <p class="text-muted">{{biography.1}}</p>
                                <p class="text-muted">{{biography.2}}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </main>
  {% endblock %}

templates/website/projects.html
{% extends "base.html" %}
{% block content %}
{% load static %}
            <!-- Projects Section-->
            <section class="py-5">
                <div class="container px-5 mb-5">
                    <div class="text-center mb-5">
                        <h1 class="display-5 fw-bolder mb-0"><span class="text-gradient d-inline">Projects</span></h1>
                    </div>
                    <div class="row gx-5 justify-content-center">
                        <div class="col-lg-11 col-xl-9 col-xxl-8">
                            <!-- Project Card 1-->
                            <div class="card overflow-hidden shadow rounded-4 border-0 mb-5">
                                <div class="card-body p-0">
                                    <div class="d-flex align-items-center">
                                        <div class="p-5">
                                            <h2 class="fw-bolder">CV Website</h2>
                                            <p>in this project i tried build a cv resume website.</p>
                                            <h4>Github link : </h4><a href="{{project_link}}">{{project_link}}</a>
                                        </div>
                                    </div>
                                </div>
                            </div>


    
{% endblock %}

templates/website/resume.html
{% extends "base.html" %}
{% block content %}
{% load static %}
            <!-- Page Content-->
            <div class="container px-5 my-5">
                <div class="text-center mb-5">
                    <h1 class="display-5 fw-bolder mb-0"><span class="text-gradient d-inline">Resume</span></h1>
                </div>
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-11 col-xl-9 col-xxl-8">
                        
                        <!-- Education Section-->
                        <section>
                          
                        </section>
                        <!-- Divider-->
                        <div class="pb-5"></div>
                        <!-- Skills Section-->
                        <section>
                            <!-- Skillset Card-->
                            <div class="card shadow border-0 rounded-4 mb-5">
                                <div class="card-body p-5">
                                    <!-- Professional skills list-->
                                    <div class="mb-5">
                                        <div class="d-flex align-items-center mb-4">
                                            <div class="feature bg-primary bg-gradient-primary-to-secondary text-white rounded-3 me-3"><i class="bi bi-book"></i></div>
                                            <h3 class="fw-bolder mb-0"><span class="text-gradient d-inline">Eductions</span></h3>
                                        </div>
                                        <div class="row row-cols-1 row-cols-md-3 mb-4">
                                            <div class="col mb-4 mb-md-0"><div class="d-flex align-items-center bg-light rounded-4 p-3 h-100">{{education}}</div></div>
                                        </div>
                                    <div class="mb-5">
                                        <div class="d-flex align-items-center mb-4">
                                            <div class="feature bg-primary bg-gradient-primary-to-secondary text-white rounded-3 me-3"><i class="bi bi-tools"></i></div>
                                            <h3 class="fw-bolder mb-0"><span class="text-gradient d-inline">Skills</span></h3>
                                        </div>
                                        <div class="row row-cols-1 row-cols-md-3 mb-4">
                                            <div class="col mb-4 mb-md-0"><div class="d-flex align-items-center bg-light rounded-4 p-3 h-100">{{skills.0}}</div></div>
                                            <div class="col mb-4 mb-md-0"><div class="d-flex align-items-center bg-light rounded-4 p-3 h-100">{{skills.1}}</div></div>
                                            <div class="col"><div class="d-flex align-items-center bg-light rounded-4 p-3 h-100">{{skills.2}}</div></div>
                                        </div>
                                        <!-- <div class="row row-cols-1 row-cols-md-3">
                                            <div class="col mb-4 mb-md-0"><div class="d-flex align-items-center bg-light rounded-4 p-3 h-100">Network Security</div></div>
                                            <div class="col mb-4 mb-md-0"><div class="d-flex align-items-center bg-light rounded-4 p-3 h-100">Adobe Software Suite</div></div>
                                            <div class="col"><div class="d-flex align-items-center bg-light rounded-4 p-3 h-100">User Interface Design</div></div>
                                        </div> -->
                                    </div>
                                    <!-- Languages list-->
                                    <div class="mb-0">
                                        <div class="d-flex align-items-center mb-4">
                                            <div class="feature bg-primary bg-gradient-primary-to-secondary text-white rounded-3 me-3"><i class="bi bi-chat-fill"></i></i></div>
                                            <h3 class="fw-bolder mb-0"><span class="text-gradient d-inline">Languages</span></h3>
                                        </div>
                                        <div class="row row-cols-1 row-cols-md-3 mb-4">
                                            <div class="col mb-4 mb-md-0"><div class="d-flex align-items-center bg-light rounded-4 p-3 h-100">{{languages.0}}</div></div>
                                            <div class="col mb-4 mb-md-0"><div class="d-flex align-items-center bg-light rounded-4 p-3 h-100">{{languages.1}}</div></div>
                                            <div class="col"><div class="d-flex align-items-center bg-light rounded-4 p-3 h-100">{{languages.2}}</div></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
        </main>
       
{% endblock %}